// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WFormsSqLite1.Data;

#nullable disable

namespace WFormsSqLite1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("WFormsSqLite1.Models.Bakery", b =>
                {
                    b.Property<int>("BakeryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BakeryId");

                    b.ToTable("Bakeries");

                    b.HasData(
                        new
                        {
                            BakeryId = 1,
                            Address = "Nowy Sącz 32-222",
                            Name = "Piekarnia sądecka"
                        },
                        new
                        {
                            BakeryId = 2,
                            Address = "Kraków 31-222",
                            Name = "Piekarz i Spółka"
                        },
                        new
                        {
                            BakeryId = 3,
                            Address = "Bochnia 34-333",
                            Name = "Staropolska Piekarnia"
                        },
                        new
                        {
                            BakeryId = 4,
                            Address = "Kraków 31-233",
                            Name = "Wypieki własne"
                        });
                });

            modelBuilder.Entity("WFormsSqLite1.Models.Cake", b =>
                {
                    b.Property<int>("CakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BakeryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("CakeId");

                    b.HasIndex("BakeryId");

                    b.ToTable("Cakes");

                    b.HasData(
                        new
                        {
                            CakeId = 1,
                            BakeryId = 1,
                            Description = "długi opis piekarni",
                            Name = "Mały Hiszpan",
                            Price = 2.66m
                        },
                        new
                        {
                            CakeId = 2,
                            BakeryId = 1,
                            Description = "długi opis piekarni",
                            Name = "Rolada mała",
                            Price = 12.99m
                        },
                        new
                        {
                            CakeId = 3,
                            BakeryId = 2,
                            Description = "długi opis piekarni",
                            Name = "Pączek średni",
                            Price = 0.99m
                        },
                        new
                        {
                            CakeId = 4,
                            BakeryId = 2,
                            Description = "długi opis piekarni",
                            Name = "Torcik wenecki",
                            Price = 8.99m
                        },
                        new
                        {
                            CakeId = 5,
                            BakeryId = 3,
                            Description = "długi opis piekarni",
                            Name = "Drożdżowe ciastko",
                            Price = 1.66m
                        },
                        new
                        {
                            CakeId = 6,
                            BakeryId = 3,
                            Description = "długi opis piekarni",
                            Name = "Tort średni",
                            Price = 7.66m
                        },
                        new
                        {
                            CakeId = 7,
                            BakeryId = 3,
                            Description = "długi opis piekarni",
                            Name = "Faworki",
                            Price = 12.89m
                        },
                        new
                        {
                            CakeId = 8,
                            BakeryId = 4,
                            Description = "długi opis piekarni",
                            Name = "Napoleon",
                            Price = 3.99m
                        });
                });

            modelBuilder.Entity("WFormsSqLite1.Models.Cake", b =>
                {
                    b.HasOne("WFormsSqLite1.Models.Bakery", "Bakery")
                        .WithMany("Cakes")
                        .HasForeignKey("BakeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bakery");
                });

            modelBuilder.Entity("WFormsSqLite1.Models.Bakery", b =>
                {
                    b.Navigation("Cakes");
                });
#pragma warning restore 612, 618
        }
    }
}
