// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMysqlDb_3tip_sp.Data;

namespace WebMysqlDb_3tip_sp.Migrations
{
    [DbContext(typeof(MySqlfilmDB))]
    partial class MySqlfilmDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("WebMysqlDb_3tip_sp.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tomasz Bomasz",
                            ReleaseDate = new DateTime(2012, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Samo zło"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Maurycy Murzecki",
                            ReleaseDate = new DateTime(2009, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rybacy"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Monika Małecka",
                            ReleaseDate = new DateTime(2004, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wisna"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Egeniusz Pawlikowski",
                            ReleaseDate = new DateTime(2013, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nie wiem"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
