// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApii60_sp.Data;

#nullable disable

namespace WebApii60_sp.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    partial class FilmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("WebApii60_sp.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2010, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Director = "Tomasz Bomasz",
                            Title = "Szeregowiec Ryan"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2010, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Director = "Helena Melena",
                            Title = "Gwiezdne wojny 1"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2010, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Director = "Tomasz Małecki",
                            Title = "Gwiezdne wojny 2"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2008, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Director = "Anna Wanna",
                            Title = "Gwinea"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(1990, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Director = "Roman Polański",
                            Title = "Wojna i Pokój"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2022, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Director = "Agta Bałata",
                            Title = "Najnowszy Film"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
