/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cw3;

public class App {
    public static String getGreeting() {
        return "Hello from 3TI_gim";
    }

    public static void main(String[] args) {
        System.out.println(getGreeting());
        FilmRepo repo = new FilmRepo();
        repo.getFilms().stream()
                .forEach(System.out::println);
    }
}
